### ISSUE TITLE
Any ideas how to make playback less memory\gc hungry?

### ISSUE THREAD

**Issue by hellozyemlya** [UjjwalT1/TroidMedia#2]
Rendering some big 60 fps video takes hell lot of memory for each frame where Bitmap is allocated.

Any ideas how to reuse\lock bitmap between vlcj render callback and main thread?

**Comment by UjjwalT1** [comment]
I dont think I do. Coz while working on this project my intention wasn't on optimising how frame buffer allocation is working. My focus was simply to make something that just works. And I failed even in that too, coz the buffer allocation only works when the application is running as a jar file and fails when running as exe.

**Comment by hellozyemlya** [comment]
Thanks for answer. Just for information - find out androidx.compose.ui.graphics.painter.Painter, it allows to implement custom bitmap painter(an alternative for androidx.compose.ui.graphics.painter.BitmapPainter). Will look further to remove allocations at all, just need to know how to repaint image.

Custom drawer allowed to reuse one skia Bitmap, where all access to it wrapped inside synchronized block(as well as resulting ImageBitmap access, that  backed by that skia Bitmap instance). That reduces allocation count a lot, now app memory usage is constant.

**Comment by hellozyemlya** [comment]
And sorry for troubling - running as exe == running from generated distributions? Probably will take a look at that issue as well, since I want to write more or less similar app. Was very surprised that something already exists, I even tend to fork, and add required functionality for my needs, but there is no license. Anyway, thanks a lot for answers and good code references.

**Comment by UjjwalT1** [comment]
running as exe == running from generated distributions? 

Yeah I meant that only .
